language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build :kategory-docs:runAnk
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # deploy release
  - provider: script
    script: ./gradlew bintrayUpload install -PdryRun=false
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^Release.*$"
  # deploy snapshot
  - provider: script
    script: ./gradlew bintrayUpload install -PdryRun=false
    on:
      branch: master
      tags: false