language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build :kategory-docs:runAnk
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # deploy release
  - provider: script
    script: deploy-scripts/deploy_release.sh
    on:
      branch: master
      tags: true
      condition: "$TRAVIS_TAG =~ ^[0-9].[0-9].[0-9]$"
  # deploy snapshot
  - provider: script
    script: deploy-scripts/deploy_snapshot.sh
    on:
      branch: master
      tags: false