language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

env:
  global:
  - secure: FqsKkQflWF2MdS9r7fFOzUlX6Vj9Mua9rh/u359EmKWY77G24WgqAChtenl9gKQ2THqSMdWaKcuLLe+XvVBJtTGpVluhIXKiEgy712pURbpRizZfuOC2m/0Cr+MebXFt088VelHj1w8Xzg1pdZLEM/7GAGCHkrxJgv11CAhEzYmSl+NZi57Wuf9V1KYginSkj6/OcVz/GcmFi3MPJT2wUhw2SfXM/syCEQ54Cp//8F4UCCq39ZITuVzVjhqI3GOJuqxHN6kWh+mtTJqmbddVUPWmSyFKeaTWemn2OivYFdCbOD/NfrSZbYJKUSnPUFS5I388gboHoKIk1Kj2YyEbXG+cmOtoP0dGiV617wOd1CJnBperQgcj2/NUs70hyxBRn970NTYTz4ARwjAlKE+RQyeWIPZqEKXW5+Al0DFEhxKPGduMAia3iVomJrTwGtHw/r5tNQwwa+sRbIjbm46e8YeUrrgQWlPx0IBR8ON00yIfxBwfReh6SxJ87A+Iqe+ovHNhcDwIn0slz8VyAhHdb5j/Amdmp0UDk4BxS+SX7lhB4EmNs5oG+7kKXkCbZ14rUMMXKCBhZkd4CxV7BvK0hr5Nzhh3fQlC9Fsl757mCsXVtM6sp/PYRwLA7N0/X38Kvd1ON3Y2uLuNSZji93PdZTDTy5zsvC4K5OFpodz0fwI=
  - secure: AcwGtBD5GP/uT3y8e9oQte3xUo/Rw2is5CvyKaQFP3rwJsFIIqo1JnP5PCy8NV4aR9EPt1bSu7l2GEtZyq0hlKtE8QBkbuX9o4qPZ4Rd1dpjxevz2rH17joy1fcaQ26Z8lIFEt7v7Xy4Iq2e1HOJiY1GAM2MZDW7udM6OmIO1ZE1eSbgOlnajoAvW3epu5PWWZM3a0Fawu5paQsi0K0Pq+xjNglyvfSKSFJ0TiFnRvRgF0tIlR6mIjQ09Mz+yO046waSAOwylSKbCAONcHPMYrLhx2/j82maQJoHLIYzdj6sMpvrTW0latUccnzvkUwsn0TsVbecGbC+Imh8sRCAMeHRL9NAqSPVtHLJKwgfZaD/u8SyNpiXGqhr6Se5f1tlAgnTyrjvyaYdXiA+UsM7051R3uMtRcfUJScjG7hhCgMOvxls4fNF+51nFS5yr3DZD7qTmYqJB1PlB4R5mVWcCsDnNQzlccYh2X76MuX60uEvdpiQ6bHgcNpOSaV8FnZdTeudSeJGtroN6x+K/oklmGnot2nCR2cBfLbCFYlJ2JjfSXFVnDfgkDugOW2qBhjNr8iimKNBmaVJR9eZZm/fCtGQ/vkL6Ue+HtWuKsErYu1CgRtgmiZJLEcbpuGJfHYRui11qrXT+t/uyq1kBRaiRhL60RFN6Lmbu3VJph75wkE=

script:
  - ./gradlew clean build :kategory-docs:runAnk
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # deploy release
  - provider: script
    script: deploy-scripts/deploy_release.sh
    on:
      branch: master
      tags: true
  # deploy snapshot
  - provider: script
    script: deploy-scripts/deploy_snapshot.sh
    on:
      branch: master