language: kotlin
sudo: required

jdk:
  - oraclejdk8

script:
  - ./gradlew wrapper
  - ./gradlew check
  - ./gradlew detekt
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
