version: 2

jobs:
  build:
    working_directory: ~/arrow
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      _JAVA_OPTIONS: -Xmx4g -Xms512m
      GRADLE_OPTS: "-Dkotlin.compiler.execution.strategy=“in-process”"
    steps:
      - checkout
      - run:
          name: Build and Docs
          command: ./gradlew clean dokka :arrow-docs:runAnk
