version: 2

jobs:
  build:
    working_directory: ~/arrow
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build and Docs
          command: ./gradlew clean build dokka :arrow-docs:runAnk
