version: 2

jobs:
  build:
    working_directory: ~/arrow
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build and Docs
          command: ./gradlew clean build dokka :arrow-docs:runAnk --no-daemon -Dorg.gradle.jvmargs="-Xms4g -Xmx4g -XX:MaxPermSize=3g" -Dkotlin.compiler.execution.strategy=in-process
